/**:
  ros__parameters:
    # boundary inflation (meters)
    region_inflation: 0.1

    # Collection =
    collection_area: [
      0.0, 1.0, 0.0, 1.0,  
      1.0, 2.0, 0.0, 1.0,  
      2.0, 3.0, 0.0, 1.0,
      3.0, 4.0, 0.0, 1.0,
      4.0, 5.0, 0.0, 1.0,   
    ]

    # Pantry 
    pantry_area: [
      10.0, 11.0, 0.0, 1.0, 
      11.0, 12.0, 0.0, 1.0 
    ]